name: producerapp
# just scale up in case you want to start producing messages
replicaCount: 1
image:
  repository: avarange/pj-ds-producer
  pullPolicy: Always

arguments:
  - Pattern
  - "50"
  - "15000"

topic: topic1
