name: producerapp
# just scale up in case you want to start producing messages
replicaCount: 1
image:
  repository: avarange/pj-ds-producer
#  repository:  k3d-monitoring-registry.localhost:12345/producerapp
  pullPolicy:  Always

arguments:
  - Pattern
  - 7
  - 10000
topic: topic1
