name: producerapp
# just scale up in case you want to start producing messages
replicaCount: 0
image:
  repository: avarange/pj-ds-producer
  pullPolicy: Always

arguments:
  - "--workload-strategy=stair"
  - "--sleeptime-seconds=30"
  - "--messages-per-minute=10000"
  - "--pattern-window=30"
  - "--seed=30"

topic: topic1
