name: producerapp
# just scale up in case you want to start producing messages
replicaCount: 0
image:
  repository: avarange/pj-ds-producer
  pullPolicy: Always

arguments:
  - Static
  - "30"
  - "1500"
  - "5"

topic: topic1
