---
# Use dummy Docker Hub Account als Workaround
- name: Login into Docker Hub
  community.docker.docker_login:
    username: "{{ vault_docker_hub_username }}"
    password: "{{ vault_docker_hub_password }}"

- name: Get consumer app version
  slurp:
    src: /root/kafka-monitoring/deployment/charts/consumerapp/Chart.yaml
  register: result

- name: Extract consumer app version
  set_fact:
    consumer_app_version: "{{ result.content | b64decode | regex_search('appVersion:\\s+\"(.*)\"', '\\1') | first }}"

- name: Building consumer app
  community.docker.docker_image:
    build:
      path: /root/kafka-monitoring/consumerapp
    name: "{{ consumer_repository }}"
    tag: "{{ repository_branch }}_{{ consumer_app_version }}"
    push: true
    source: build

- name: Get producer app version
  slurp:
    src: /root/kafka-monitoring/deployment/charts/producerapp/Chart.yaml
  register: result

- name: Extract producer app version
  set_fact:
    producer_app_version: "{{ result.content | b64decode | regex_search('appVersion:\\s+\"(.*)\"', '\\1') | first }}"

- name: Building producer app
  community.docker.docker_image:
    build:
      path: /root/kafka-monitoring/producerapp
    name: "{{ producer_repository }}"
    tag: "{{ repository_branch }}_{{ producer_app_version }}"
    push: true
    source: build

- name: Update helm repo for consumer app
  lineinfile:
    path: /root/kafka-monitoring/deployment/charts/consumerapp/values.yaml
    regexp: "^\\s+repository: .*"
    line: "  repository: avarange/pj-ds-consumer"

- name: Update helm repo for producer app
  lineinfile:
    path: /root/kafka-monitoring/deployment/charts/producerapp/values.yaml
    regexp: "^\\s+repository: .*"
    line: "  repository: avarange/pj-ds-producer"
