helmfiles:
  - path: helmfile-stack.yaml

helmDefaults:
  wait: true
  waitForJobs: true
  createNamespace: false
  timeout: 600

releases:
  - name: producerapp
    namespace: kafka
    chart: "./charts/producerapp"

  - name: consumerapp
    namespace: kafka
    chart: "./charts/consumerapp"
    needs:
      - kafka/producerapp
