
repositories:
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/
  - name: strimzi
    url: https://strimzi.io/charts/
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: kedacore
    url: https://kedacore.github.io/charts
  - name: confluentinc
    url: https://confluentinc.github.io/cp-helm-charts/
  - name: redpanda
    url: https://charts.redpanda.com/

helmDefaults:
  wait: true
  waitForJobs: true
  createNamespace: false
  timeout: 600

releases:
  - name: namespaces
    namespace: default
    chart: "./charts/namespace"
    values:
      - "./manifests/namespaces.yaml"

  - name: metrics-server
    namespace: kube-system
    chart: metrics-server/metrics-server
    version: 3.10.0
    values:
      - args:
          - "--kubelet-insecure-tls"
    needs:
      - default/namespaces

  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 47.2.1
    disableValidationOnInstall: true
    values:
      - "./manifests/kube-prometheus-stack.yaml"
    needs:
      - default/namespaces

  - name: keda
    namespace: keda
    chart: kedacore/keda
    values:
      - "./manifests/keda.yaml"
    needs:
      - monitoring/kube-prometheus-stack

  - name: strimzi
    namespace: strimzi
    chart: strimzi/strimzi-kafka-operator
    version: 0.34.0
    values:
      - "./manifests/strimzi.yaml"
    needs:
      - monitoring/kube-prometheus-stack

  - name: strimzi-kafka
    namespace: kafka
    disableValidationOnInstall: true
    chart: "./charts/kafka-cluster"
    needs:
      - strimzi/strimzi

  - name: redpanda-console
    namespace: kafka
    chart: "redpanda/console"
    version: 0.5.6
    values:
      - "./manifests/redpanda-console.yaml"
    needs:
      - kafka/strimzi-kafka
