helmfiles:
  - path: helmfile-stack.yaml

releases:
  - name: producerapp
    namespace: kafka
    chart: "./charts/producerapp"
    needs:
      - kafka/redpanda-console

  - name: consumerapp
    namespace: kafka
    chart: "./charts/consumerapp"
    needs:
      - kafka/producerapp
