---
- name: Creating VMs if necessary
  include_tasks:
    file: init.yml
    apply:
      tags:
        - init
  tags:
    - init

- name: Starting all VMs
  include_tasks:
    file: start.yml
    apply:
      tags:
        - start
  tags:
    - start

- name: Stopping all VMs
  include_tasks:
    file: stop.yml
    apply:
      tags:
        - stop
  tags:
    - stop
