---
- name: Creating VMs if necessary
  include_tasks:
    file: init.yml
    apply:
      tags:
        - init
  tags:
    - init
    - ssh

- name: Starting all VMs
  include_tasks:
    file: start.yml
    apply:
      tags:
        - start
  tags:
    - start
    - init

- name: Stopping all VMs
  include_tasks:
    file: stop.yml
    apply:
      tags:
        - stop
  tags:
    - stop

- name: Delete all VMs
  include_tasks:
    file: delete.yml
    apply:
      tags:
        - delete
  tags:
    - delete
