name: consumerapp
replicaCount: 1
image:
  repository: avarange/pj-ds-consumer
#  repository:  k3d-monitoring-registry.localhost:12345/consumerapp
  pullPolicy:  Always
port: 8080
labels:

service:
  port: 80

autoscaling:
  minReplicas: 1
  maxReplicas: 24
  scaleUp:
    scaleUpWindow: 30
    policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 30
  scaleDown:
    scaleDownWindow: 180
    policies:
      - type: Percent
        value: 100
        periodSeconds: 120
      - type: Pods
        value: 4
        periodSeconds: 60
  hpa:
    enabled: true
    targetCPUUtilizationPercentage: 80
  keda:
    enabled: false
    pollingInterval: 30
    cooldownPeriod: 180
    triggers:
#      - type: cpu
#        metricType: Utilization
#        metadata:
#          value: "90"
      - type: kafka
        metadata:
          bootstrapServers: cluster-kafka-bootstrap.kafka:9092
          consumerGroup: group1
          lagThreshold: "1000"
          offsetResetPolicy: latest

resources:
  limits:
    cpu: "250m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "512Mi"

arguments:
  - CPU

topic: topic1
