name: consumerapp
replicaCount: 1
image:
  repository: avarange/pj-ds-consumer
#  repository:  k3d-monitoring-registry.localhost:12345/consumerapp
  pullPolicy:  Always
port: 8080
labels:

service:
  port: 80

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 24
  targetCPUUtilizationPercentage: 80
  scaleUp:
    scaleUpWindow: 30
    policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 15
  scaleDown:
    scaleDownWindow: 30
    policies:
      - type: Percent
        value: 100
        periodSeconds: 120
      - type: Pods
        value: 2
        periodSeconds: 15

resources:
  limits:
    cpu: "250m"
    memory: "256Mi"

arguments:
  - CPU

topic: topic1
