name: consumerapp
replicaCount: 1
image:
  pullPolicy:  Always

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 12
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
  scaleUpWindow: 60
  scaleDownWindow: 120

resources:
  limits:
    cpu: "250m"
    memory: "128Mi"

arguments:
  - CPU

topic: topic1
