name: consumerapp
replicaCount: 1
image:
  repository: avarange/pj-ds-consumer
#  repository:  k3d-monitoring-registry.localhost:12345/consumerapp
  pullPolicy:  Always
port: 8080
labels:

service:
  port: 80

autoscaling:
  minReplicas: 1
  maxReplicas: 24
  scaleUp:
    scaleUpWindow: 30
    policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 15
  scaleDown:
    scaleDownWindow: 120
    policies:
      - type: Percent
        value: 100
        periodSeconds: 120
      - type: Pods
        value: 4
        periodSeconds: 30
  # TODO: transfer HPA ownership (https://keda.sh/docs/2.11/concepts/scaling-deployments/#transfer-ownership-of-an-existing-hpa)
  hpa:
    enabled: false
    targetCPUUtilizationPercentage: 80
  keda:
    enabled: true
    pollingInterval: 30
    cooldownPeriod: 120
    triggers:
      - type: cpu
        metricType: Utilization
        metadata:
          value: 80
      - type: kafka
        metadata:
          bootstrapServers: cluster-kafka-bootstrap.kafka:9092
          consumerGroup: group1
          lagThreshold: "40000"
          offsetResetPolicy: latest

resources:
  limits:
    cpu: "250m"
    memory: "256Mi"

arguments:
  - CPU

topic: topic1
