name: consumerapp
replicaCount: 1
image:
  repository: avarange/pj-ds-consumer
#  repository:  k3d-monitoring-registry.localhost:12345/consumerapp
  pullPolicy:  Always
port: 8080
labels:

service:
  port: 80

autoscaling:
  minReplicas: 1
  maxReplicas: 24
  scaleUp:
    scaleUpWindow: 15
    policies:
      - type: Pods
        value: 8
        periodSeconds: 15
  scaleDown:
    scaleDownWindow: 300
    policies:
      - type: Pods
        value: 2
        periodSeconds: 30
  hpa:
    enabled: true
    targetCPUUtilizationPercentage: 80
  keda:
    enabled: false
    pollingInterval: 30
    cooldownPeriod: 300
    triggers:
      - type: cpu
        metricType: Utilization
        metadata:
          value: "80"
      - type: kafka
        metadata:
          bootstrapServers: cluster-kafka-bootstrap.kafka:9092
          consumerGroup: group1
          topic: topic1
          lagThreshold: "1000"
          offsetResetPolicy: latest

resources:
  limits:
    cpu: "250m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "512Mi"

arguments:
  - "--utilization-strategy=CPU"

topic: topic1
