name: consumerapp
replicaCount: 1
image:
  repository: k3d-monitoring-registry.localhost:12345/consumerapp
  pullPolicy:  Always
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 12
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
  scaleUpWindow: 0
  scaleDownWindow: 300
resources:
  limits:
    cpu: "250m"
    memory: "128Mi"
arguments:
  - CPU
topic: topic1
