name: consumerapp
replicaCount: 1
image:
  repository: avarange/pj-ds-consumer
  pullPolicy:  Always
port: 8080
labels:

service:
  port: 80

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 24
  targetCPUUtilizationPercentage: 80
  scaleUp:
    scaleUpWindow: 30
    policies:
      - type: Percent
        value: 100
        periodSeconds: 30
  scaleDown:
    scaleDownWindow: 60
    policies:
      - type: Percent
        value: 100
        periodSeconds: 60

resources:
  limits:
    cpu: "250m"
    memory: "256Mi"

arguments:
  - CPU

topic: topic1
