name: consumerapp
replicaCount: 1
image:
  repository: 192.168.252.146:5000/pj-ds/consumerapp
  # for local development
  # repository: k3d-monitoring-registry.localhost:12345/consumerapp
  pullPolicy:  Always
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 12
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
resources:
  limits:
    cpu: "250m"
    memory: "128Mi"
arguments:
  - CPU
topic: topic1
