{
 "title": "workload-monitoring",
 "time": { "from": "2023-06-27T20:40:00.000Z", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Consumergroup total lag over all partitions",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag_sum{consumergroup=\"group1\"}",
     "legendFormat": "Lag sum for consumergroup {{ consumergroup }}"
    },
    {
     "expr": "sum by(topic) (rate(kafka_topic_partition_current_offset{topic=\"topic1\"}[1m]) * 60 ) / 2",
     "legendFormat": "messages in per minute"
    }
   ]
  },
  {
   "title": "CPU Utilization in Percent over all consumerapps",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(avg without(pod) (sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"kafka\", container=\"consumerapp\", pod=~\".*consumerapp.*\"}[5m])) / max by (pod) (kube_pod_container_resource_limits{namespace=\"kafka\", container=\"consumerapp\", pod=~\".*consumerapp.*\", resource=\"cpu\"}))) * 100",
     "legendFormat": "CPU Utilization in Percent over all consumerapps"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{metric_name=\"cpu\"}",
     "legendFormat": "HPA CPU Target Limit"
    }
   ]
  },
  {
   "title": "Message processing latency in seconds per consumerapp",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "message_latency_seconds_max{application=\"consumerapp\"}",
     "legendFormat": "{{ appId }}"
    },
    {
     "expr": "avg by(application) (message_latency_seconds_max{application=\"consumerapp\"})",
     "legendFormat": "average over all"
    }
   ]
  },
  {
   "title": "Average Memory Usage over all consumerapps",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "100 * (avg by (container) (irate(container_cpu_usage_seconds_total{namespace=\"kafka\",container=\"consumerapp\",pod=~\".*consumerapp.*\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization in Percentage for each consumer app",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 11 },
   "targets": [
    {
     "expr": "(sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"kafka\", container=\"consumerapp\", pod=~\".*consumerapp.*\"}[5m])) / (max by (pod) (kube_pod_container_resource_limits{namespace=\"kafka\", container=\"consumerapp\", pod=~\".*consumerapp.*\", resource=\"cpu\"}))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current/Desired consumer replicas",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{horizontalpodautoscaler=\"consumerapp\"}",
     "legendFormat": "Current replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas{horizontalpodautoscaler=\"consumerapp\"}",
     "legendFormat": "Desired replicas"
    }
   ]
  },
  {
   "title": "Memory (Mi) per pod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{namespace=\"kafka\", container=\"consumerapp\", pod=~\".*consumerapp.*\"} / (1024*1024)) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"kafka\", container=\"consumerapp\", pod=~\".*consumerapp.*\"}) by (container) / (1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU (cores) per consumer pod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 21 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"kafka\", container=\"consumerapp\", pod=~\".*consumerapp.*\"}[5m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max by(container) (kube_pod_container_resource_limits{namespace=\"kafka\", container=\"consumerapp\", resource=\"cpu\"})",
     "legendFormat": "CPU Limit"
    }
   ]
  }
 ]
}