{
 "title": "workload-monitoring",
 "time": { "from": "2023-06-22T08:10:00.000Z", "to": "2023-06-22T09:30:00.000Z" },
 "panels": [
  {
   "title": "Consumergroup total lag over all partitions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag_sum{consumergroup=\"group1\"}",
     "legendFormat": "Lag sum for consumergroup {{ consumergroup }}"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"topic1\"}[1m]) * 60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current/Desired consumer replicas",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{horizontalpodautoscaler=\"consumerapp\"}",
     "legendFormat": "Current replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas{horizontalpodautoscaler=\"consumerapp\"}",
     "legendFormat": "Desired replicas"
    }
   ]
  },
  {
   "title": "CPU Utilization in Percent over all consumerapps",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(avg without(pod) (sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"kafka\", container=\"consumerapp\", pod=~\".*consumerapp.*\"}[5m])) / max by (pod) (kube_pod_container_resource_limits{namespace=\"kafka\", container=\"consumerapp\", pod=~\".*consumerapp.*\", resource=\"cpu\"}))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Memory Usage over all consumerapps",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100 * (avg by (container) (irate(container_cpu_usage_seconds_total{namespace=\"kafka\",container=\"consumerapp\",pod=~\".*consumerapp.*\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU (cores) per consumer pod",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"kafka\", container=\"consumerapp\", pod=~\".*consumerapp.*\"}[5m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"kafka\", container=\"consumerapp\", pod=~\".*consumerapp.*\", resource=\"cpu\"}",
     "legendFormat": "CPU Limit"
    }
   ]
  },
  {
   "title": "CPU Utilization in Percentage for each consumer app",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 20 },
   "targets": [
    {
     "expr": "(sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"kafka\", container=\"consumerapp\", pod=~\".*consumerapp.*\"}[5m])) / (max by (pod) (kube_pod_container_resource_limits{namespace=\"kafka\", container=\"consumerapp\", pod=~\".*consumerapp.*\", resource=\"cpu\"}))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory (Mi) per pod",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{namespace=\"kafka\", container=\"consumerapp\", pod=~\".*consumerapp.*\"} / (1024*1024)) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"kafka\", container=\"consumerapp\", pod=~\".*consumerapp.*\"}) by (container) / (1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}