{
 "title": "workload-monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Consumergroup total lag over all partitions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag_sum{consumergroup=\"group1\"}",
     "legendFormat": "Lag sum for consumergroup {{ consumergroup }}"
    }
   ]
  },
  {
   "title": "Current/Desired consumer replicas",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{horizontalpodautoscaler=\"consumerapp\"}",
     "legendFormat": "Current replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas{horizontalpodautoscaler=\"consumerapp\"}",
     "legendFormat": "Desired replicas"
    }
   ]
  },
  { "title": "CPU (cores) per consumer pod", "gridPos": { "h": 12, "w": 6, "x": 0, "y": 8 } },
  {
   "title": "CPU Utilization in Percentage for each consumer app",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "(sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"kafka\", container=\"consumerapp\", pod=~\".*consumerapp.*\"}[5m])) / (max by (pod) (kube_pod_container_resource_limits{namespace=\"kafka\", container=\"consumerapp\", pod=~\".*consumerapp.*\", resource=\"cpu\"}))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory (Mi) per pod", "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 } },
  {
   "title": "CPU Utilization in Percent over all consumerapps",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "(avg without(pod) (sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"kafka\", container=\"consumerapp\", pod=~\".*consumerapp.*\"}[5m])) / max by (pod) (kube_pod_container_resource_limits{namespace=\"kafka\", container=\"consumerapp\", pod=~\".*consumerapp.*\", resource=\"cpu\"}))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Memory Usage over all consumerapps",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "100 * (avg by (container) (irate(container_cpu_usage_seconds_total{namespace=\"kafka\",container=\"consumerapp\",pod=~\".*consumerapp.*\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}