{
 "title": "workload-monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Consumergroup total lag over all partitions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag_sum{consumergroup=\"group1\"}",
     "legendFormat": "Lag sum for consumergroup {{ consumergroup }}"
    }
   ]
  },
  {
   "title": "Current/Desired consumer replicas",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{horizontalpodautoscaler=\"consumerapp\"}",
     "legendFormat": "Current replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas{horizontalpodautoscaler=\"consumerapp\"}",
     "legendFormat": "Desired replicas"
    }
   ]
  },
  {
   "title": "CPU Utilization of all consumerapps",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"kafka\", pod=~\".*consumerapp.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}