---
- name: Install packages for kubernetes
  apt:
    name:
      - ca-certificates
      - curl

- name: Download public key for repository
  get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /tmp/kubernetes_apt-key.gpg

- name: Deamor public key
  command: >
    gpg --batch --dearmor
    -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
    /tmp/kubernetes_apt-key.gpg
  register: result
  failed_when: result.rc != 0 and "File exists" not in result.stderr
  changed_when: false

- name: Delete optional old repository source
  file:
    state: absent
    path: /etc/apt/sources.list.d/kubernetes.list
    force: true

- name: Add repository as source
  lineinfile:
    path: /etc/apt/sources.list.d/kubernetes.list
    line: deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    create: true
    mode: 0700

- name: Install kubernetes
  apt:
    name:
      - kubeadm
      - kubelet
      - kubectl
    update_cache: true

- name: Create sysctl file for Kubernetes
  copy:
    content: ""
    dest: /etc/sysctl.d/99-kubernetes.conf
    force: false
    mode: 0700

- name: Enable IPv4 Forwarding
  lineinfile:
    path: /etc/sysctl.d/99-kubernetes.conf
    line: "{{ item }}"
  with_items:
    - 'net.ipv4.ip_forward = 1'

- name: Apply sysctl params without reboot
  command: sysctl --system
  changed_when: false

- name: Reset old Kubernetes configuration
  command: kubeadm reset -f
  changed_when: false

- name: Delete old Kubernetes configuration files
  file:
    state: absent
    path: /root/.kube
    force: true

- name: Recreate configuration folder
  file:
    state: directory
    path: /root/.kube
    force: true
    mode: 0700

- name: Init Kubernetes for Controller
  command: kubeadm init
  changed_when: false

- name: Copy configuration
  copy:
    src: /etc/kubernetes/admin.conf
    remote_src: true
    dest: /root/.kube/config
    owner: root
    group: root
    mode: u+rw,o-rwx,g-rwx
    force: true

- name: Get join command
  command: kubeadm token create --print-join-command
  register: result
  changed_when: false

- name: Parse join command
  set_fact:
    join_command: "{{ result.stdout_lines[0] }}"
