---
- name: Delete old Kubernetes configuration files
  file:
    state: absent
    path: /root/.kube
    force: true

- name: Recreate configuration folder
  file:
    state: directory
    path: /root/.kube
    force: true
    mode: 0700

- name: Get local network address
  shell: |
    set -o pipefail
    ip --json a s | jq -r '.[] | if .ifname == "ens4" then .addr_info[] | if .family == "inet" then .local else empty end else empty end'
  args:
    executable: /bin/bash
  register: result
  failed_when: result.rc != 0 or not result.stdout
  changed_when: false
  tags:
    - join

- name: Parse local network address
  set_fact:
    local_address: "{{ result.stdout }}"
  tags:
    - join

- name: Init Kubernetes for Controller
  command: >
    kubeadm init
    --apiserver-advertise-address="{{ local_address }}"
    --apiserver-cert-extra-sans="{{ local_address }}"
    --pod-network-cidr="192.168.0.0/16"
  changed_when: false

- name: Copy configuration
  copy:
    src: /etc/kubernetes/admin.conf
    remote_src: true
    dest: /root/.kube/config
    owner: root
    group: root
    mode: u+rw,o-rwx,g-rwx
    force: true

- name: Install network plugin - Callisto
  command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
  changed_when: false

- name: Get join command
  command: kubeadm token create --print-join-command
  register: result
  changed_when: false
  tags:
    - join

- name: Parse join command
  set_fact:
    join_command: "{{ result.stdout_lines[0] }}"
  tags:
    - join
