---
- name: Install Kubernetes
  include_tasks:
    file: kubernetes.yml
    apply:
      tags:
        - kubernetes
        - setup
  tags:
    - kubernetes

- name: Install Helm, Helm-Diff and HelmFile
  include_tasks:
    file: helm.yml
    apply:
      tags:
        - helm
        - setup
  tags:
    - helm  