---
- name: Download Docker public key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker_apt-key.gpg

- name: Dearmor public key
  command: >
    gpg --batch --dearmor
    -o /etc/apt/keyrings/docker.gpg
    /tmp/docker_apt-key.gpg
  register: result
  failed_when: result.rc != 0 and "File exists" not in result.stderr
  changed_when: false

- name: Delete optional old repository source
  file:
    state: absent
    path: /etc/apt/sources.list.d/docker.list
    force: true

- name: Add repository as source
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: deb [signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable
    create: true
    mode: 0700

- name: Install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true

- name: Copy default Containerd configuration
  shell: /usr/bin/containerd config default > /etc/containerd/config.toml
  changed_when: false

- name: Eenable and restart Containerd
  systemd:
    name: containerd
    state: restarted
    enabled: true
    daemon-reload: true
