---
- name: Install Docker
  include_tasks:
    file: docker.yml
    apply:
      tags:
        - docker
        - setup
  tags:
    - docker

- name: Install Utils
  import_tasks:
    file: utils.yml