---
- name: Install Docker
  include_tasks:
    file: tasks/docker.yml
    apply:
      tags:
        - docker
        - setup
  tags:
    - docker

- name: Install Utils
  include_tasks:
    file: tasks/utils.yml
