---
# Default values
# -----------------------------------------------------------------
# Consumer
autoscaling_enabled: true
autoscaling_min_replicas: 1
autoscaling_max_replicas: 24
autoscaling_scale_up: 
  window: 15
  policies:
    # - type: percent
    #   value: 100
    #   period_seconds: 60
    - type: Pods
      value: 2
      period_seconds: 45
autoscaling_scale_down:
  window: 300
  policies:
    - type: percent
      value: 100
      period_seconds: 120
    - type: Pods
      value: 4
      period_seconds: 60
autoscaling_hpa:
  enabled: true
  target_cpu_util: 80
autoscaling_keda:
  enabled: false
  polling_interval: 30
  cooldown_period: 300
  trigger_cpu_value: 80
  trigger_kafka_lag_threshold: 1000

# Producer
# Choose: Static, Pattern, Random, Stair
producer_workload_pattern: Static
producer_pattern_window: 30
producer_messages_per_minute: 1500
producer_sleep_time: 5
producer_replica_count: 1

# Resources
autoscaling_resources:
  limits:
    cpu: "250m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "512Mi"


# Experiment Series
# -----------------------------------------------------------------
# - Add more rounds here for adding additional experiements to series
# - Be sure to add all field for dicts like scale_up/down or keda
# - Duration in hours
experiments:
  - name: Round 1
    duration: 2.5
    values:
      autoscaling_enabled: true
      autoscaling_min_replicas: 1
      autoscaling_max_replicas: 24
      autoscaling_scale_up: 
        window: 15
        policies:
          - type: Pods
            value: 2
            period_seconds: 45
      autoscaling_scale_down:
        window: 300
        policies:
          - type: percent
            value: 100
            period_seconds: 120
          - type: Pods
            value: 4
            period_seconds: 60
      autoscaling_hpa:
        enabled: true
        target_cpu_util: 80
      autoscaling_keda:
        enabled: false
        polling_interval: 30
        cooldown_period: 300
        trigger_cpu_value: 80
        trigger_kafka_lag_threshold: 1000
  - name: Round 2
    duration: 2.5
    values:
      autoscaling_enabled: true
      autoscaling_min_replicas: 1
      autoscaling_max_replicas: 24
      autoscaling_scale_up: 
        window: 15
        policies:
          - type: Pods
            value: 2
            period_seconds: 45
      autoscaling_scale_down:
        window: 300
        policies:
          - type: percent
            value: 100
            period_seconds: 120
          - type: Pods
            value: 4
            period_seconds: 60
      autoscaling_hpa:
        enabled: true
        target_cpu_util: 80
      autoscaling_keda:
        enabled: false
        polling_interval: 30
        cooldown_period: 300
        trigger_cpu_value: 80
        trigger_kafka_lag_threshold: 1000
  - name: Round 3
    duration: 2.5
    values:
      autoscaling_enabled: true
      autoscaling_min_replicas: 1
      autoscaling_max_replicas: 24
      autoscaling_scale_up: 
        window: 15
        policies:
          - type: Pods
            value: 2
            period_seconds: 45
      autoscaling_scale_down:
        window: 300
        policies:
          - type: percent
            value: 100
            period_seconds: 120
          - type: Pods
            value: 4
            period_seconds: 60
      autoscaling_hpa:
        enabled: true
        target_cpu_util: 80
      autoscaling_keda:
        enabled: false
        polling_interval: 30
        cooldown_period: 300
        trigger_cpu_value: 80
        trigger_kafka_lag_threshold: 1000
