---
# Default values
# -----------------------------------------------------------------
# Kafka
# kafka_partitions will only be used if kafka_enforce_partitions is
# true. Default is the value of autoscaling_max_replicas
kafka_topic: topic1
kafka_enforce_partitions: false
kafka_partitions: -1

# Consumer
autoscaling_enabled: true
autoscaling_min_replicas: 1
autoscaling_max_replicas: 24
autoscaling_scale_up:
  window: 0
  policies:
    - type: Percent
      value: 100
      period_seconds: 15
    - type: Pods
      value: 4
      period_seconds: 15
autoscaling_scale_down:
  window: 300
  policies:
    - type: Percent
      value: 100
      period_seconds: 15
    #- type: Pods
    #  value: 4
    #  period_seconds: 60
# be aware that HPA and KEDA are exclusive - choose one of them by setting "enabled" to true or false exclusively
autoscaling_hpa:
  enabled: true
  target_cpu_util: 80
autoscaling_keda:
  enabled: false
  polling_interval: 30
  cooldown_period: 300
  trigger_cpu_value: 80
  trigger_kafka_lag_threshold: 100
autoscaling_util_strategy: CPU

# Producer
# Choose: Static, Pattern, Random, Stair
producer_workload_pattern: Stair
producer_pattern_window: 30
producer_seed: 30
producer_messages_per_minute: 10000
producer_sleep_time: 5
producer_replica_count: 1

# Resources
# KEDA only takes the requests into account!
autoscaling_resources:
  limits:
    cpu: "250m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "512Mi"


# Experiment Series
# -----------------------------------------------------------------
# - Add more rounds here for adding additional experiements to series
# - Be sure to add all field for dicts like scale_up/down or keda
# - Duration in hours
experiments:
  - name: Round 6
    duration: 2.5
    values:
      autoscaling_enabled: true
      autoscaling_min_replicas: 1
      autoscaling_max_replicas: 24
      autoscaling_scale_up:
        window: 15
        policies:
          - type: Pods
            value: 4
            period_seconds: 15
      autoscaling_scale_down:
        window: 180
        policies:
          - type: Pods
            value: 2
            period_seconds: 15
      autoscaling_hpa:
        enabled: true
        target_cpu_util: 85
      autoscaling_keda:
        enabled: false
        polling_interval: 30
        cooldown_period: 300
        trigger_cpu_value: 80
        trigger_kafka_lag_threshold: 1000
  - name: Round 7
    duration: 2.5
    values:
      autoscaling_enabled: true
      autoscaling_min_replicas: 1
      autoscaling_max_replicas: 24
      autoscaling_scale_up:
        window: 15
        policies:
          - type: Pods
            value: 4
            period_seconds: 15
      autoscaling_scale_down:
        window: 180
        policies:
          - type: Pods
            value: 2
            period_seconds: 15
      autoscaling_hpa:
        enabled: true
        target_cpu_util: 90
      autoscaling_keda:
        enabled: false
        polling_interval: 30
        cooldown_period: 300
        trigger_cpu_value: 80
        trigger_kafka_lag_threshold: 1000
# NEW!
  - name: Round 1
    duration: 3.0
    values:
      autoscaling_enabled: true
      autoscaling_min_replicas: 1
      autoscaling_max_replicas: 24
      autoscaling_scale_up:
        window: 15
        policies:
          - type: Pods
            value: 4
            period_seconds: 15
      autoscaling_scale_down:
        window: 180
        policies:
          - type: Pods
            value: 2
            period_seconds: 15
      autoscaling_hpa:
        enabled: true
        target_cpu_util: 60
      autoscaling_keda:
        enabled: false
        polling_interval: 30
        cooldown_period: 300
        trigger_cpu_value: 80
        trigger_kafka_lag_threshold: 1000
  - name: Round 2
    duration: 3.0
    values:
      autoscaling_hpa:
        enabled: true
        target_cpu_util: 65
  - name: Round 2
    duration: 3.0
    values:
      autoscaling_hpa:
        enabled: true
        target_cpu_util: 70
  - name: Round 3
    duration: 3.0
    values:
      autoscaling_hpa:
        enabled: true
        target_cpu_util: 75
  - name: Round 4
    duration: 3.0
    values:
      autoscaling_hpa:
        enabled: true
        target_cpu_util: 80
  - name: Round 5
    duration: 3.0
    values:
      autoscaling_hpa:
        enabled: true
        target_cpu_util: 85
  - name: Round 6
    duration: 3.0
    values:
      autoscaling_hpa:
        enabled: true
        target_cpu_util: 90
