{{- if .Values.autoscaling.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "consumerapp.fullname" . }}
  labels:
    {{- include "consumerapp.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "consumerapp.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.autoscaling.hpa.scaleUp.scaleUpWindow }}
      policies:
        {{- toYaml .Values.autoscaling.hpa.scaleUp.policies | nindent 8 }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.hpa.scaleDown.scaleDownWindow }}
      policies:
        {{- toYaml .Values.autoscaling.hpa.scaleDown.policies | nindent 8 }}
  metrics:
    {{- if .Values.autoscaling.hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.hpa.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
    {{- end }}
{{- end }}
