apiVersion: v1
kind: Service
metadata:
  name: {{ include "consumerapp.fullname" . }}
  labels:
    {{- include "consumerapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "consumerapp.selectorLabels" . | nindent 4 }}
