---
- name: Reset old Kubernetes configuration
  command: kubeadm reset -f
  changed_when: false
  tags:
    - never
    - join

- name: Check if Node(s) can reach Kubernetes Controller
  wait_for: "host={{ hostvars[groups['kubernetes_controllers'][0]]['local_address'] }} port=6443 timeout=1"
  tags:
    - join

- name: Join Kubernetes Cluster
  command: "{{ hostvars[groups['kubernetes_controllers'][0]].join_command }}"
  changed_when: false
  tags:
    - join
