[virtual_machines]
backend-producer ansible_host=104.155.62.246
consumer ansible_host=34.78.90.205

[localhost]
127.0.0.1

[kubernetes_controllers]
backend-producer ansible_host=34.22.239.204

[kubernetes_nodes]
consumer ansible_host=34.79.152.170
