---
- name: Setup and Control GCP [if needed]
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
    - gcp  
- name: Install and Setup Docker and Kubernetes [if needed]
  hosts: virtual_machines
  roles:
    - setup
  tags:
    - never
    - setup
